# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: "atlassian/default-image:2"
pipelines: 
  branches: 
    feature/*: 
      - 
        step: 
          artifacts: 
            - node_modules/**
          caches: 
            - node
          name: Installation
          script: 
            - "npm install"
    master: 
      - 
        step: 
          artifacts: 
            - node_modules/**
          caches: 
            - node
          name: Installation
          script: 
            - "npm install"
      - 
        step: 
          name: "Deploy to Github"
          script: 
            - "git push --mirror git@github.com:akmiDev/akmiDev.github.io.git"
  default: 
    - 
      step: 
        artifacts: 
          - node_modules/**
        caches: 
          - node
        name: Installation
        script: 
          - "npm install"